project: molecular_rdkit
provider: local
registry: data/registry.db
offline_store:
  type: postgres
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  database: ${POSTGRES_DB}
  db_schema: public
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
online_store:
  type: sqlite
  path: data/online_store.db
entity_key_serialization_version: 3
auth:
  type: no_auth
